export const golangQuestions = [
    { topic: "Go", text: "Go foi criado no Google por Robert Griesemer, Rob Pike, Ken Thompson.", answer: true, explanation: "✅ VERDADEIRO! Anunciado em 2009 como projeto interno do Google." },
    { topic: "Go", text: "Go utiliza coleta de lixo (garbage collector) desde sua primeira versão.", answer: true, explanation: "✅ VERDADEIRO! GC concorrente com pausas otimizadas, evoluiu muito nas versões recentes." },
    { topic: "Go", text: "Go é uma linguagem dinamicamente tipada como Python e JavaScript.", answer: false, explanation: "❌ FALSO! Go é estaticamente tipado, com tipos verificados em tempo de compilação." },
    { topic: "Go", text: "Go suporta herança de classes como Java e C++.", answer: false, explanation: "❌ FALSO! Go usa composição via embedding em vez de herança tradicional." },
    { topic: "Go", text: "Interfaces em Go são satisfeitas implicitamente, sem declaração explícita.", answer: true, explanation: "✅ VERDADEIRO! Se um tipo implementa os métodos da interface, ele a satisfaz automaticamente." },
    { topic: "Go", text: "Goroutines são threads do sistema operacional gerenciadas pelo kernel.", answer: false, explanation: "❌ FALSO! Goroutines são threads leves gerenciadas pela runtime do Go, não pelo SO." },
    { topic: "Go", text: "Channels são a forma recomendada de comunicação entre goroutines.", answer: true, explanation: "✅ VERDADEIRO! Channels seguem o princípio: 'Não comunique por memória compartilhada; compartilhe memória por comunicação'." },
    { topic: "Go", text: "A declaração 'select' permite que uma goroutine aguarde múltiplas operações de channel.", answer: true, explanation: "✅ VERDADEIRO! Select bloqueia até que um dos seus cases possa ser executado." },
    { topic: "Go", text: "A palavra-chave 'defer' executa uma função imediatamente, antes da linha atual.", answer: false, explanation: "❌ FALSO! Defer adia a execução até o retorno da função atual (último a entrar, primeiro a sair)." },
    { topic: "Go", text: "Panic e recover são mecanismos similares a exceptions para tratamento de erros.", answer: true, explanation: "✅ VERDADEIRO! Porém, Go prefere retorno explícito de erros; panic é para situações inesperadas." },
    { topic: "Go", text: "Go modules (go.mod) foram introduzidos apenas no Go 1.16.", answer: false, explanation: "❌ FALSO! Go modules foram introduzidos experimentalmente no 1.11 e estáveis no 1.13." },
    { topic: "Go", text: "go fmt é uma ferramenta oficial que formata código Go de forma padronizada.", answer: true, explanation: "✅ VERDADEIRO! Elimina discussões sobre estilo de formatação no time." },
    { topic: "Go", text: "go build compila o código e gera um arquivo executável estaticamente linkado.", answer: true, explanation: "✅ VERDADEIRO! Por padrão, produz binário standalone sem dependências externas." },
    { topic: "Go", text: "go run compila o código mas não executa, apenas verifica erros.", answer: false, explanation: "❌ FALSO! go run compila E executa o programa imediatamente." },
    { topic: "Go", text: "go test procura automaticamente por arquivos terminados em _test.go.", answer: true, explanation: "✅ VERDADEIRO! Convenção que dispensa configuração adicional." },
    { topic: "Go", text: "Benchmarks em Go requerem bibliotecas externas como Google Benchmark.", answer: false, explanation: "❌ FALSO! Benchmark é nativo com funções BenchmarkXxx e comando 'go test -bench'." },
    { topic: "Go", text: "Table-driven tests são uma prática comum para testar múltiplos cenários.", answer: true, explanation: "✅ VERDADEIRO! Usa slice de structs com entradas e saídas esperadas." },
    { topic: "Go", text: "O pacote 'context' é usado apenas para logging e debugging.", answer: false, explanation: "❌ FALSO! Context propaga cancellation, deadlines e valores request-scoped através de APIs." },
    { topic: "Go", text: "Slices em Go são arrays de tamanho fixo que não podem crescer.", answer: false, explanation: "❌ FALSO! Slices são referências a arrays subjacentes e podem crescer com append." },
    { topic: "Go", text: "Maps em Go são seguros para concorrência sem sincronização adicional.", answer: false, explanation: "❌ FALSO! Maps não são thread-safe; use mutex ou sync.Map para concorrência." },
    { topic: "Go", text: "Structs em Go podem ter métodos associados (func receivers).", answer: true, explanation: "✅ VERDADEIRO! Métodos podem ter receiver por valor ou ponteiro." },
    { topic: "Go", text: "Embedding em Go permite herança múltipla de comportamento.", answer: true, explanation: "✅ VERDADEIRO! Composição via embedding promove campos/métodos do tipo embutido." },
    { topic: "Go", text: "interface{} em Go pode armazenar qualquer valor, similar ao any.", answer: true, explanation: "✅ VERDADEIRO! Go 1.18 introduziu 'any' como alias para interface{}." },
    { topic: "Go", text: "Type assertion sem a forma 'comma ok' pode causar panic se o tipo for incompatível.", answer: true, explanation: "✅ VERDADEIRO! Use 'value, ok := i.(T)' para evitar panic." },
    { topic: "Go", text: "Type switch em Go só funciona com tipos básicos (int, string, etc).", answer: false, explanation: "❌ FALSO! Type switch funciona com qualquer tipo de interface." },
    { topic: "Go", text: "Go 1.18 introduziu suporte a generics na linguagem.", answer: true, explanation: "✅ VERDADEIRO! Type parameters, constraints, e pacote 'slices' e 'maps' experimentais." },
    { topic: "Go", text: "Constraints em Go generics são sempre definidas por interfaces.", answer: true, explanation: "✅ VERDADEIRO! Usa-se 'interface{ int | float64 }' para definir union de tipos." },
    { topic: "Go", text: "Goroutines são diretamente mapeadas 1:1 para threads do sistema operacional.", answer: false, explanation: "❌ FALSO! Goroutines são multiplexadas (M:N) em menos threads do SO." },
    { topic: "Go", text: "WaitGroup é usado para aguardar um grupo de goroutines finalizar.", answer: true, explanation: "✅ VERDADEIRO! Add, Done e Wait são os métodos principais." },
    { topic: "Go", text: "Mutual exclusion (mutex) é a única forma de sincronização em Go.", answer: false, explanation: "❌ FALSO! Além de mutex, Go tem channels, atomic, WaitGroup, Once, etc." },
    { topic: "Go", text: "sync.Once garante que uma função seja executada apenas uma vez.", answer: true, explanation: "✅ VERDADEIRO! Útil para inicialização lazy e singleton." },
    { topic: "Go", text: "Operações atômicas (sync/atomic) são sempre mais lentas que mutex.", answer: false, explanation: "❌ FALSO! Atomic são geralmente mais rápidos para operações simples sem contenção." },
    { topic: "Go", text: "Go workspace (go.work) permite desenvolvimento multi-módulo local.", answer: true, explanation: "✅ VERDADEIRO! Introduzido no Go 1.18, facilita desenvolvimento com módulos locais." },
    { topic: "Go", text: "Go não possui suporte nativo a servidores HTTP.", answer: false, explanation: "❌ FALSO! O pacote net/http é parte da biblioteca padrão e muito poderoso." },
    { topic: "Go", text: "ServeMux é o roteador HTTP padrão da biblioteca padrão.", answer: true, explanation: "✅ VERDADEIRO! Também chamado de 'DefaultServeMux'." },
    { topic: "Go", text: "encoding/json em Go usa reflection para serialização/deserialização.", answer: true, explanation: "✅ VERDADEIRO! Tags como `json:\"nome\"` controlam o mapeamento." },
    { topic: "Go", text: "Gin, Echo e Fiber são frameworks da biblioteca padrão do Go.", answer: false, explanation: "❌ FALSO! São frameworks de terceiros; a stdlib tem net/http." },
    { topic: "Go", text: "GORM é um ORM popular para Go com suporte a associações e hooks.", answer: true, explanation: "✅ VERDADEIRO! GORM é amplamente usado para acesso a banco de dados." },
    { topic: "Go", text: "sqlx é uma extensão do pacote database/sql que adiciona funcionalidades.", answer: true, explanation: "✅ VERDADEIRO! Adiciona NamedExec, StructScan, e outros helpers." },
    { topic: "Go", text: "Makefiles são a forma padrão de automação em projetos Go.", answer: false, explanation: "❌ FALSO! Go prefere ferramentas como Taskfile ou Mage; Makefile é opcional." },
    { topic: "Go", text: "Air é uma ferramenta de hot-reload para desenvolvimento Go.", answer: true, explanation: "✅ VERDADEIRO! Reinicia automaticamente o servidor em mudanças de código." },
    { topic: "Go", text: "Delve (dlv) é o debugger oficial do Go, com suporte a breakpoints.", answer: true, explanation: "✅ VERDADEIRO! Integrado com VS Code, GoLand, etc." },
    { topic: "Go", text: "pprof é uma ferramenta exclusiva para profiling de memória apenas.", answer: false, explanation: "❌ FALSO! pprof também faz profiling de CPU, goroutines, mutex, heap, etc." },
    { topic: "Go", text: "race detector (go test -race) encontra data races em tempo de execução.", answer: true, explanation: "✅ VERDADEIRO! Instrumenta o código para detectar acessos concorrentes não sincronizados." },
    { topic: "Go", text: "Go trata erros com exceptions, similar ao try-catch do Java.", answer: false, explanation: "❌ FALSO! Go usa retorno explícito de erros (multiple returns), não exceptions." },
    { topic: "Go", text: "errors.Is e errors.As foram introduzidos no Go 1.13.", answer: true, explanation: "✅ VERDADEIRO! Facilitam comparação e desempacotamento de erros." },
    { topic: "Go", text: "Go é amplamente usado para microsserviços devido à sua baixa latência.", answer: true, explanation: "✅ VERDADEIRO! Binários pequenos, inicialização rápida, e excelente concorrência." },
    { topic: "Go", text: "O compilador Go (gc) não suporta cross-compilation para outros OS.", answer: false, explanation: "❌ FALSO! Go suporta cross-compilation nativamente com variáveis GOOS e GOARCH." },
    { topic: "Go", text: "Vetor (vector) é um tipo nativo em Go para listas dinâmicas.", answer: false, explanation: "❌ FALSO! Go usa 'slice' como o tipo nativo para listas dinâmicas, não vetor." },
    { topic: "Go", text: "O comando 'go mod tidy' adiciona dependências ausentes e remove não utilizadas.", answer: true, explanation: "✅ VERDADEIRO! Mantém o go.mod e go.sum limpos e consistentes." },

];