export const kafkaQuestions = [

    { topic: "Kafka", text: "Kafka armazena mensagens em tópicos, que são particionados.", answer: true, explanation: "✅ VERDADEIRO! Partitions permitem paralelismo e escalabilidade." },
    { topic: "Kafka", text: "Cada mensagem em Kafka tem uma chave que determina a partição.", answer: true, explanation: "✅ VERDADEIRO! Mesma chave vai mesma partição (garante ordenação)." },
    { topic: "Kafka", text: "Consumer groups permitem que múltiplos consumidores leiam partições em paralelo.", answer: true, explanation: "✅ VERDADEIRO! Cada partição é lida por apenas um consumidor do grupo." },
    { topic: "Kafka", text: "Kafka remove mensagens imediatamente após serem consumidas.", answer: false, explanation: "❌ FALSO! Kafka retém mensagens baseado em política de retenção (tempo/tamanho)." },
    { topic: "Kafka", text: "Offset é o identificador único de mensagens dentro de uma partição.", answer: true, explanation: "✅ VERDADEIRO! Consumidor confirma offsets processados." },
    { topic: "Kafka", text: "Kafka usa protocolo push (broker envia mensagens para consumidores).", answer: false, explanation: "❌ FALSO! Kafka usa PULL: consumidores requisitam mensagens." },
    { topic: "Kafka", text: "ZooKeeper é obrigatório no Kafka?, depende da versão.", answer: true, explanation: "✅ VERDADEIRO! Até versão 2.8 requer ZooKeeper; 3.0+ pode usar KRaft (sem ZK)." },
    { topic: "Kafka", text: "Log compaction mantém apenas a última mensagem de cada chave.", answer: true, explanation: "✅ VERDADEIRO! Útil para cenários de estado (ex: tabela de referência)." },
    { topic: "Kafka", text: "Kafka Streams é uma biblioteca para processamento de streams dentro do Kafka.", answer: true, explanation: "✅ VERDADEIRO! Processamento stateful e stateless." },
    { topic: "Kafka", text: "Kafka Connect importa/exporta dados entre Kafka e outros sistemas.", answer: true, explanation: "✅ VERDADEIRO! Conectores JDBC, S3, Elasticsearch etc." },
    { topic: "Kafka", text: "Kafka é mais lento que RabbitMQ em cenários de roteamento complexo.", answer: true, explanation: "✅ VERDADEIRO! RabbitMQ tem roteamento mais flexível (exchanges)." },
    { topic: "Kafka", text: "Kafka é ideal para processamento de streams em tempo real.", answer: true, explanation: "✅ VERDADEIRO! Alta vazão, retenção, replay." },
    { topic: "Kafka", text: "Kafka suporta transações atômicas entre múltiplas partições.", answer: true, explanation: "✅ VERDADEIRO! Idempotência e transações (exactly-once)." },
    { topic: "Kafka", text: "Ack=0 no Kafka garante que mensagem foi escrita em todos os réplicas.", answer: false, explanation: "❌ FALSO! Ack=0 não espera confirmação; Ack=all espera todas réplicas." },
    { topic: "Kafka", text: "Replication factor determina número de cópias de cada partição.", answer: true, explanation: "✅ VERDADEIRO! Alta disponibilidade." },
    { topic: "Kafka", text: "Leader partition coordena escrita e leitura.", answer: true, explanation: "✅ VERDADEIRO! Follower réplicas sincronizam passivamente." },
    { topic: "Kafka", text: "ISR (In-Sync Replicas) são réplicas atrasadas em relação ao líder.", answer: false, "explicaion": "❌ FALSO! ISR são réplicas sincronizadas (sem atraso além do tolerável)." },
    { topic: "Kafka", text: "Kafka tem ordem de mensagens garantida globalmente no tópico.", answer: false, explanation: "❌ FALSO! Ordem garantida APENAS dentro de cada partição." },
    { topic: "Kafka", text: "Producer pode escolher enviar mensagem para partição específica.", answer: true, explanation: "✅ VERDADEIRO! Via Partitioner customizado ou chave." },
    { topic: "Kafka", text: "Kafka usa conciliação de partição para balanceamento automático.", answer: true, explanation: "✅ VERDADEIRO! Rebalanceamento de consumers." },
    { topic: "Kafka", text: "Kafka armazena offsets no próprio Kafka (tópico __consumer_offsets).", answer: true, explanation: "✅ VERDADEIRO! Desde versão 0.9." },
    { topic: "Kafka", text: "Kafka suporta dead letter queue nativamente.", answer: false, explanation: "❌ FALSO! Não nativamente; implementado via conector ou tópico separado." },
    { topic: "Mensageria", text: "At-least-once delivery garante que mensagem não é perdida, mas pode ser duplicada.", answer: true, explanation: "✅ VERDADEIRO! Compromisso comum em ambos RabbitMQ e Kafka." },
    { topic: "Mensageria", text: "At-most-once delivery é mais seguro para dados financeiros.", answer: false, explanation: "❌ FALSO! At-most-once pode perder dados; finanças prefere at-least-once com idempotência." },
    { topic: "Mensageria", text: "Exactly-once delivery é possível com configurações adequadas.", answer: true, explanation: "✅ VERDADEIRO! Kafka com transações e idempotência; RabbitMQ com transações e deduplicação." }
];