export const rabbitMqQuestions = [
    { topic: "RabbitMQ", text: "RabbitMQ implementa o protocolo AMQP 0-9-1.", answer: true, explanation: "✅ VERDADEIRO! Advanced Message Queuing Protocol é o protocolo nativo do RabbitMQ." },
    { topic: "RabbitMQ", text: "RabbitMQ suporta apenas o protocolo AMQP, não MQTT ou STOMP.", answer: false, explanation: "❌ FALSO! RabbitMQ suporta múltiplos protocolos via plugins: MQTT, STOMP, AMQP 1.0." },
    { topic: "RabbitMQ", text: "Exchange é responsável por rotear mensagens para as filas.", answer: true, explanation: "✅ VERDADEIRO! Produtor envia para exchange, que decide para qual(is) fila(s) entregar." },
    { topic: "RabbitMQ", text: "Em uma direct exchange, a routing key deve corresponder exatamente ao nome da fila.", answer: false, explanation: "❌ FALSO! Deve corresponder à routing key do binding, não necessariamente ao nome da fila." },
    { topic: "RabbitMQ", text: "Topic exchange permite usar curingas como * (uma palavra) e # (zero ou mais palavras).", answer: true, explanation: "✅ VERDADEIRO! Ex: 'stock.*' casa com 'stock.usd' mas não com 'stock.usd.nyse'." },
    { topic: "RabbitMQ", text: "Fanout exchange envia mensagens para uma única fila baseada em routing key.", answer: false, explanation: "❌ FALSO! Fanout ignora routing key e envia para TODAS filas ligadas." },
    { topic: "RabbitMQ", text: "Messages são persistentes quando marcadas como persistent e a queue é durável.", answer: true, explanation: "✅ VERDADEIRO! Sobrevivem a reinicialização do broker." },
    { topic: "RabbitMQ", text: "Publisher confirms garantem que mensagem foi recebida pelo broker.", answer: true, explanation: "✅ VERDADEIRO! Mecanismo de confirmação assíncrona." },
    { topic: "RabbitMQ", text: "Consumer ACK automático é recomendado para processamento crítico.", answer: false, explanation: "❌ FALSO! ACK manual é preferível para garantir processamento (at-most-once vs at-least-once)." },
    { topic: "RabbitMQ", text: "Prefetch count limita número de mensagens não confirmadas por consumidor.", answer: true, explanation: "✅ VERDADEIRO! Evita sobrecarga do consumidor." },
    { topic: "RabbitMQ", text: "Dead Letter Exchange (DLX) armazena mensagens rejeitadas ou expiradas.", answer: true, explanation: "✅ VERDADEIRO! Útil para tratamento de erros e monitoramento." },
    { topic: "RabbitMQ", text: "TTL (Time-to-Live) pode ser aplicado apenas a filas, não a mensagens individuais.", answer: false, explanation: "❌ FALSO! TTL pode ser definido por mensagem (expiration) ou por fila (x-message-ttl)." },
    { topic: "RabbitMQ", text: "Quorum queues oferecem maior consistência e resiliência.", answer: true, explanation: "✅ VERDADEIRO! Baseadas no protocolo Raft, replicação síncrona." },
    { topic: "RabbitMQ", text: "Streams no RabbitMQ são apenas para logs, não para mensageria.", answer: false, explanation: "❌ FALSO! Streams são filas com armazenamento persistente e replay de mensagens." },
    { topic: "RabbitMQ", text: "Shovels movem mensagens entre clusters ou datacenters.", answer: true, explanation: "✅ VERDADEIRO! Plug-in de replicação." },
    { topic: "RabbitMQ", text: "Federation conecta exchanges e filas entre diferentes brokers.", answer: true, explanation: "✅ VERDADEIRO! Distribuição geográfica." },
    { topic: "RabbitMQ", text: "RabbitMQ é recomendado para throughput muito alto (milhões de msgs/s).", answer: false, explanation: "❌ FALSO! Kafka é melhor para alto throughput; RabbitMQ ótimo para roteamento complexo." },
    { topic: "RabbitMQ", text: "RabbitMQ suporta mensagens transacionais (txSelect, txCommit).", answer: true, explanation: "✅ VERDADEIRO! Mas pode impactar performance; publisher confirms são preferíveis." },
    { topic: "RabbitMQ", text: "Alternate exchanges redirecionam mensagens não roteáveis.", answer: true, explanation: "✅ VERDADEIRO! Evita perda de mensagens." },
    { topic: "RabbitMQ", text: "Clustering em RabbitMQ replica dados entre todos nós automaticamente.", answer: false, explanation: "❌ FALSO! Clustering não replica filas (apenas metadados). Use quorum queues." },
    { topic: "RabbitMQ", text: "Consumidores podem usar basicQos para limitar prefetch.", answer: true, explanation: "✅ VERDADEIRO! Controle de fluxo." },
    { topic: "RabbitMQ", text: "Management plugin expõe UI e API HTTP.", answer: true, explanation: "✅ VERDADEIRO! Monitoramento e administração." },
    { topic: "RabbitMQ", text: "RabbitMQ tem alta performance para mensagens grandes (> 10MB).", answer: false, explanation: "❌ FALSO! Ambos têm limitações; Kafka melhor para mensagens grandes." },
    { topic: "RabbitMQ", text: "Header exchange roteia baseado em cabeçalhos, não routing key.", answer: true, explanation: "✅ VERDADEIRO! Mais flexível que direct/topic." },

];